//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSoft.CS2SPCustomFields.AutoField
{


    public partial class AutoWithFormatFieldControl
    {        
        protected global::Microsoft.SharePoint.WebControls.RenderingTemplate AutoFieldControl;
        protected global::System.Web.UI.WebControls.Literal LiteralFieldFormat;
    }
}
