//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListViewFilter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListViewFilter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListViewFilter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListViewFilter.Resources.ListViewFilter", typeof(ListViewFilter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string Caption_Caption {
            get {
                return ResourceManager.GetString("Caption_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control type.
        /// </summary>
        public static string Caption_ControlType {
            get {
                return ResourceManager.GetString("Caption_ControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Caption_Field {
            get {
                return ResourceManager.GetString("Caption_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Caption_Position {
            get {
                return ResourceManager.GetString("Caption_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields settings.
        /// </summary>
        public static string Caption_SettingsDialog {
            get {
                return ResourceManager.GetString("Caption_SettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete.
        /// </summary>
        public static string ControlType_Autocomplete {
            get {
                return ResourceManager.GetString("ControlType_Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        public static string ControlType_Boolean {
            get {
                return ResourceManager.GetString("ControlType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ControlType_Date {
            get {
                return ResourceManager.GetString("ControlType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range.
        /// </summary>
        public static string ControlType_DateRange {
            get {
                return ResourceManager.GetString("ControlType_DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDown List.
        /// </summary>
        public static string ControlType_DropDownList {
            get {
                return ResourceManager.GetString("ControlType_DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple DropDown List.
        /// </summary>
        public static string ControlType_DropDownListWithSettings {
            get {
                return ResourceManager.GetString("ControlType_DropDownListWithSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Group.
        /// </summary>
        public static string ControlType_PeoplePicker {
            get {
                return ResourceManager.GetString("ControlType_PeoplePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple User or Group.
        /// </summary>
        public static string ControlType_PeoplePickerWithMultiSelect {
            get {
                return ResourceManager.GetString("ControlType_PeoplePickerWithMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy term.
        /// </summary>
        public static string ControlType_Taxonomy {
            get {
                return ResourceManager.GetString("ControlType_Taxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple taxonomy terms.
        /// </summary>
        public static string ControlType_TaxonomyMultiValue {
            get {
                return ResourceManager.GetString("ControlType_TaxonomyMultiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        public static string ControlType_Text {
            get {
                return ResourceManager.GetString("ControlType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox with settings.
        /// </summary>
        public static string ControlType_TextWithOptions {
            get {
                return ResourceManager.GetString("ControlType_TextWithOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for SharePoint List.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin with.
        /// </summary>
        public static string FilterType_BeginWith {
            get {
                return ResourceManager.GetString("FilterType_BeginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string FilterType_Contains {
            get {
                return ResourceManager.GetString("FilterType_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        public static string FilterType_Equal {
            get {
                return ResourceManager.GetString("FilterType_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal.
        /// </summary>
        public static string FilterType_NotEqual {
            get {
                return ResourceManager.GetString("FilterType_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FilterValue_All {
            get {
                return ResourceManager.GetString("FilterValue_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string FilterValue_Blank {
            get {
                return ResourceManager.GetString("FilterValue_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string FilterValue_False {
            get {
                return ResourceManager.GetString("FilterValue_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string FilterValue_IsNull {
            get {
                return ResourceManager.GetString("FilterValue_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string FilterValue_True {
            get {
                return ResourceManager.GetString("FilterValue_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Link_FieldSettings {
            get {
                return ResourceManager.GetString("Link_FieldSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Link_SolutionDescription {
            get {
                return ResourceManager.GetString("Link_SolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        public static string Link_SolutionDetails {
            get {
                return ResourceManager.GetString("Link_SolutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select.
        /// </summary>
        public static string Text_ClickToSelect {
            get {
                return ResourceManager.GetString("Text_ClickToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Text_From {
            get {
                return ResourceManager.GetString("Text_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Text_Info {
            get {
                return ResourceManager.GetString("Text_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no any field in this filter..
        /// </summary>
        public static string Text_NoFields {
            get {
                return ResourceManager.GetString("Text_NoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebPart is not connected to ListView WebPart.
        /// </summary>
        public static string Text_NotConnected {
            get {
                return ResourceManager.GetString("Text_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Connect SPListViewFilter webpart to ListView webpart.&lt;br/&gt;
        ///2. Customize fields showing in filter using webpart &lt;a href=&quot;#&quot; onclick=&quot;javascript:MSOTlPn_ShowToolPane2(&apos;Edit&apos;,&apos;{0}&apos;);&quot;&quot;&gt;setting panel&lt;/a&gt;..
        /// </summary>
        public static string Text_ShowEditPanel {
            get {
                return ResourceManager.GetString("Text_ShowEditPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Text_To {
            get {
                return ResourceManager.GetString("Text_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SQL queries to retrieve data from content DB.
        /// </summary>
        public static string Text_UseSqlQueries {
            get {
                return ResourceManager.GetString("Text_UseSqlQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List filter.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ToolTip_About {
            get {
                return ResourceManager.GetString("ToolTip_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string ToolTip_Advanced {
            get {
                return ResourceManager.GetString("ToolTip_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolTip_Settings {
            get {
                return ResourceManager.GetString("ToolTip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ToolTip_View {
            get {
                return ResourceManager.GetString("ToolTip_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string WebPart_Category {
            get {
                return ResourceManager.GetString("WebPart_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurable list filter.
        /// </summary>
        public static string WebPart_Description {
            get {
                return ResourceManager.GetString("WebPart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string WebPart_Group {
            get {
                return ResourceManager.GetString("WebPart_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List filter.
        /// </summary>
        public static string WebPart_Title {
            get {
                return ResourceManager.GetString("WebPart_Title", resourceCulture);
            }
        }
    }
}
