//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace Officience.IBNF.CurrencyField
{

    public partial class CurrencyWithSymbolFieldEditor
    {
        protected global::System.Web.UI.UserControl FilterLookupFieldSection;
        protected global::System.Web.UI.WebControls.DropDownList listTargetWeb;
        protected global::System.Web.UI.WebControls.DropDownList listTargetList;
        protected global::System.Web.UI.WebControls.DropDownList listTargetColumn;
        protected global::System.Web.UI.WebControls.DropDownList listInputType;
        protected global::System.Web.UI.WebControls.TextBox txtNumberFormat;
    }
}