//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officience.IBNF.CurrencyField {
    
    
    public partial class CurrencyWithSymbolFieldControl {        
        protected global::Microsoft.SharePoint.WebControls.RenderingTemplate CurrencyFieldControl;
        protected global::System.Web.UI.WebControls.TextBox CurrencyValue;
        protected global::System.Web.UI.WebControls.DropDownList CurrencySymbolLeft;
        protected global::System.Web.UI.WebControls.DropDownList CurrencySymbolRight;
    }
}
